### ISSUE TITLE
use only three output

### ISSUE THREAD

**Issue by LaurentDelaon** [Jean-MarcHarvengt/VGA_t4#6]
Hi Jean Marc,

I need explanation about the output wire  of your library.

Taking as example Red component. Seem you use resistor to modify voltage and add each R1 R2 R3  into one R.
Is it right ? how did the divide voltage is doing ?

A question why don't you add it into the teensy these values  and write directly on one output R ?
this is avoiding resistors...

**Comment by Jean-MarcHarvengt** [comment]
VGA is analog.
There is no analog output on the Teensy 4.0 (only PWM, no DAC as on the teensy 3.6 and anyway you would need 3)  and that would need to be driven by DMA anyway.

Anyway you frame buffer is a digital representation of the image. Each byte is 3 bits for Red, 3bits for Green and 2bits for blue. The 3 resistors (2 for blue) act as a digital to analog converter which then goes to the analog output of the VGA and that for each component. Depending on the bit output for the 3 red outputs, you actually control the level of the analog red. Same for green and blue.

By keeping everything digital at the output, you can use a shift register to control the bits as digital output on the teensy.

I hope it clarifies...
By the way, there are many libraries doing the same, ay be better explained.
uVGA for teensy 3.6,  picoVGA for the raspberry PICO...
